### ISSUE TITLE
Cut v1.15.0 Release on February 15, 2024

### ISSUE THREAD

**Issue by phisco** [crossplane/release#2]
```[tasklist]
### Possible Blockers
- [ ] https://github.com/crossplane/crossplane/pull/5365
- [ ] https://github.com/crossplane/crossplane/pull/5391#pullrequestreview-1880036069
- [x] https://github.com/crossplane/crossplane/issues/5368
- [ ] https://github.com/crossplane/crossplane/pull/5367
- [ ] https://github.com/crossplane/crossplane/pull/5373
```

This issue can be closed when we have completed the following steps (in order).
Please ensure all artifacts (PRs, workflow runs, Tweets, etc) are linked from
this issue for posterity. Refer to this [prior release issue][release-1.14.0] for
examples of each step, assuming release vX.Y.0 is being cut.

### Code Freeze

- [x] **[In Crossplane Runtime]**: Prepared the release branch `release-X.Y`:
  - [x] Created the release branch using the [GitHub UI][create-branch].
  - [x] (On the **Master** Branch) Created and merged an empty commit with `git commit --allow-empty -s -m "Empty commit after release-X.Y"`
  - [x] (On the **Master** Branch) Run the [Tag workflow][tag-workflow-runtime] with the release candidate tag for the next release `vX.Y+1.0-rc.0`. => cut https://github.com/crossplane/crossplane-runtime/releases/tag/v1.16.0-rc.1 too in the end, some time had passed since we cut rc.0 already
  - [x] (On the **Release** Branch) Run the [Tag workflow][tag-workflow-runtime] with the release candidate tag for the next release `vX.Y.0-rc.1` (assuming the latest rc tag for `vX.Y.0` is `vX.Y.0-rc.0`).  => cut https://github.com/crossplane/crossplane-runtime/releases/tag/v1.15.0-rc.1 too in the end, some time had passed since we cut rc.0 already
- [x] **[In Core Crossplane]:** Prepared the release branch `release-X.Y`:
  - [x] Created the release branch using the [GitHub UI][create-branch].
  - [x] (On the **Master** Branch) created and merged a PR bumping the Crossplane Runtime dependency to the release candidate tag from master, `vX.Y+1.0-rc.0`. => https://github.com/crossplane/crossplane/pull/5345
  - [x] (On the **Release** Branch) created and merged a PR bumping the Crossplane Runtime dependency to the release candidate tag on the release branch, `vX.Y.0-rc.1`. => https://github.com/crossplane/crossplane/pull/5344
  - [x] (On the **Master** Branch) Run the [Tag workflow][tag-workflow] with the release candidate tag for the next release, `vX.Y+1.0-rc.0`. => https://github.com/crossplane/crossplane/releases/tag/v1.16.0-rc.0
- [x] **[In Core Crossplane]:** Cut a Crossplane **release candidate** from the release branch `release-X.Y`:
  - [x] (On the **Release** Branch) Run the [Tag workflow][tag-workflow] with the release candidate tag for the release `vX.Y.0-rc.1` (assuming the latest rc tag for `vX.Y.0` is `vX.Y.0-rc.0`). => https://github.com/crossplane/crossplane/releases/tag/v1.15.0-rc.1
  - [x] (On the **Release** Branch) Run the [CI workflow][ci-workflow] and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel, e.g. `build/release-X.Y/vX.Y.0-rc.1/...` should contain all the relevant binaries. => https://github.com/crossplane/crossplane/actions/runs/7813193800
  - [x] (On the **Release** Branch) Run the [Promote workflow][promote-workflow] with channel `stable`, remember to tick the pre-release box, and verify:
    - [x] The tagged build version exists on the [releases.crossplane.io] `stable` channel at `stable/vX.Y.0-rc.1/...`.
    - [x] The tagged build is NOT marked as "current" in [stable/current/version](https://releases.crossplane.io/stable/current/version).
    - [x] Ensured that the release candidate is visible on the stable helm repo with: `helm repo add crossplane-stable https://charts.crossplane.io/stable --force-update &&  helm search repo crossplane-stable --devel`.
  - [x] Published a [new release] for the tagged version as `pre-release`, with the same name as the version, taking care of generating the changes list selecting as "Previous tag" `vX.<Y-1>.0`, so the first of the releases for the previous minor.
    - [x] Select the `Set as a pre-release` and `Create a discussion for this release` checkboxes. 
    - [x] Do NOT select the `Set as the latest release` checkbox.
  - [x] Ensured that users have been notified about the release candidate on the `#announcement` channel of the Crossplane's Slack workspace.

### Release

- [x] Opened a [docs release issue]
- [ ] ~Checked that the [GitHub milestone] for this release only contains closed issues.~
  - @jbw976 skipping this for now in the anticipation of patch releases over the next few weeks
- [x] Cut a Crossplane Runtime version and consume it from Crossplane.
  - [x] **[In Crossplane Runtime]**: Run the [Tag workflow][tag-workflow-runtime] on the `release-X.Y` branch with the proper release version, `vX.Y.0`. Message suggested, but not required: `Release vX.Y.0`.
  - [x] **[In Core Crossplane]:** (On the **Release** Branch) Update the Crossplane Runtime dependency to `vX.Y.0`.
- [x] (On the **Release** Branch) Run the [Tag workflow][tag-workflow] with the proper release version, `vX.Y.0`. Message suggested, but not required: `Release vX.Y.0`.
- [x] (On the **Release** Branch) Run the [CI workflow][ci-workflow] and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel, e.g. `build/release-X.Y/vX.Y.0/...` should contain all the relevant binaries.
- [x] (On the **Release** Branch) Run the [Promote workflow][promote-workflow] with channel `stable` and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel at `stable/vX.Y.0/...`.
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes, taking care of generating the changes list selecting as "Previous tag" `vX.<Y-1>.0`, so the first of the releases for the previous minor. Before publishing the release notes, set them as Draft and ask the rest of the team to double check them.
- [x] Checked that the [docs release issue] created previously has been completed.
- [x] Updated, in a single PR, the following on `master`:
  - [x] The [releases table] in the `README.md`, removing the now old unsupported release and adding the new one.
  - [x] The `baseBranches` list in `.github/renovate.json5`, removing the now old unsupported release and adding the new one.
- [ ] ~Closed the GitHub milestone for this release.~
  - @jbw976 skipping this for now in the anticipation of patch releases over the next few weeks
- [x] Publish a blog post about the release to the [crossplane blog]
  - https://blog.crossplane.io/crossplane-v1-15/
  - https://blog.crossplane.io/new-default-crossplane-registry-in-crossplane-1-15/
- [x] Ensured that users have been notified of the release on all communication channels:
  - [x] Slack: `#announcements` channel on Crossplane's Slack workspace.
    - https://crossplane.slack.com/archives/CEFQCGW1H/p1708018552402609
  - [x] Twitter: reach out to a Crossplane maintainer or steering committee member, see [OWNERS.md][owners].
    - https://twitter.com/crossplane_io/status/1758187078733742485
  - [x] LinkedIn: same as Twitter
    - https://www.linkedin.com/feed/update/urn:li:share:7163953112095842305/
- [x] Request @jbw976 to remove all old docs versions from Google Search
- [x] Remove any extra permissions given to release team members for this release

[Code Freeze]: https://docs.crossplane.io/knowledge-base/guides/release-cycle/#code-freeze
[ci-workflow]: https://github.com/crossplane/crossplane/actions/workflows/ci.yml
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/workflows/configurations.yml
[create-branch]: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository
[docs release issue]: https://github.com/crossplane/docs/issues/new?assignees=&labels=release&template=new_release.md&title=Release+Crossplane+version...+
[new release]: https://github.com/crossplane/crossplane/releases/new
[owners]: https://github.com/crossplane/crossplane/blob/master/OWNERS.md
[promote-workflow]: https://github.com/crossplane/crossplane/actions/workflows/promote.yml
[release-1.14.0]: https://github.com/crossplane/crossplane/issues/4871
[releases table]: https://github.com/crossplane/crossplane#releases
[releases.crossplane.io]: https://releases.crossplane.io
[tag-workflow-runtime]: https://github.com/crossplane/crossplane-runtime/actions/workflows/tag.yml
[tag-workflow]: https://github.com/crossplane/crossplane/actions/workflows/tag.yml
[GitHub milestone]: https://github.com/crossplane/crossplane/milestones
[crossplane blog]: https://blog.crossplane.io

**Comment by phisco** [comment]
holding off waiting for https://github.com/crossplane/crossplane/issues/5287, as the feature flag will be disabled by default and it wouldn't make sense to cut an RC with it enabled instead.

**Comment by phisco** [comment]
Proceeded with the release process, waiting to sync with the rest of the team before cutting an RC to discuss the updated timeline.

**Comment by negz** [comment]
@phisco I don't want to have SSA claims in alpha very long. Ideally they'd get to beta in v1.16. Let's mention that on the release notes for v1.15, e.g.:

* Behavior change coming in 1.16
* Test your compositions with the alpha flag before you upgrade

**Comment by phisco** [comment]
Sure @negz! Could be worth creating a tracking issue for its promotion to beta and add that to the 1.16 milestone then.

**Comment by jbw976** [comment]
Checklist is complete, v1.15.0 is released! 🎉 
https://github.com/crossplane/crossplane/releases/tag/v1.15.0
